# Generated by Django 4.2.29 on 2026-03-18 06:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_id', models.UUIDField(blank=True, null=True)),
                ('review_type', models.CharField(choices=[('annual', 'Annual'), ('mid_year', 'Mid-Year'), ('probation', 'Probation'), ('360', '360 Degree')], default='annual', max_length=20)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('self_review', 'Self Review'), ('manager_review', 'Manager Review'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=1, help_text='1.0 to 5.0', max_digits=3, null=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('development_plan', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('target_value', models.DecimalField(decimal_places=4, default=Decimal('100'), max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('unit', models.CharField(default='%', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='performance.goal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
