# Generated by Django 4.2.29 on 2026-03-18 06:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('calculating', 'Calculating'), ('review', 'Under Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_employer_nssf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('journal_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('component_type', models.CharField(choices=[('basic', 'Basic Salary'), ('allowance', 'Allowance'), ('deduction', 'Deduction'), ('benefit', 'Benefit')], max_length=20)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_statutory', models.BooleanField(default=False, help_text='PAYE, NSSF, NHIF, etc.')),
                ('affects_nssf', models.BooleanField(default=False)),
                ('affects_nhif', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('paye_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('nssf_employee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Employee NSSF contribution', max_digits=10)),
                ('nssf_employer', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Employer NSSF contribution', max_digits=10)),
                ('nhif_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='SHA/NHIF monthly contribution', max_digits=10)),
                ('housing_levy', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Affordable Housing Levy 1.5%', max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('lines', models.JSONField(default=list, help_text='Breakdown of all components')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.salarycomponent')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
